name: Step 4b # Copilot on GitHub

on:
  # Trigger if PR Description is edited
  # Disabled because PR summaries are not available for free accounts
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - edited

  # Trigger if Copilot adds a review comment
  pull_request_review:

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: read
  repository-projects: read

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: dev-pods/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.1

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      # START: Check practical exercise

      - name: Check for PR description
        continue-on-error: true
        id: check-pr-description
        run: |
          # Check if PR has a description and minimum length
          min_length=15
          body_length=$(echo "$PR_Body" | wc -c)
          echo "PR description length: $body_length"

          if [ "$body_length" -lt $min_length ]; then
            echo "::error::A descrição do PR é muito curta ou não foi preenchida"
            exit 1
          fi
        env:
          PR_Body: ${{ github.event.pull_request.body }}

      - name: Check for Copilot review
        id: check-copilot-review
        run: |
          # Check for a PR Review from Copilot
          reviews=$(gh pr view --repo $REPO $PR_NUMBER --json reviews)
          authors=$(echo "$reviews" | jq '.reviews[].author.login')

          if echo "$authors" | grep -q "copilot-pull-request-reviewer"; then
            echo "Copilot has reviewed this PR."
          else
            echo "Copilot has NOT reviewed this PR."
            echo "::error::No review from Copilot found"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        continue-on-error: true

      - name: Build message - step results
        id: build-message-step-results
        uses: dev-pods/action-text-variables@v0.0.1
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          template-vars: |
            step_number: 4
            passed: ${{ !contains(steps.*.outcome, 'failure') }}
            results_table:
              - description: "O pull request contém uma descrição válida"
                passed: ${{ steps.check-pr-description.outcome == 'success' }}
              - description: "O pull request recebeu uma revisão do GitHub Copilot"
                passed: ${{ steps.check-copilot-review.outcome == 'success' }}
            tips:
              - "Se você já solicitou a revisão do Copilot e esta verificação não passou, vá para a aba [actions](https://github.com/${{github.repository}}/actions) do seu repositório para verificar se há uma execução de fluxo de trabalho aguardando sua aprovação manual."
              - "Você pode usar rulesets do repositório para exigir automaticamente uma revisão do Copilot."

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

      # END: Check practical exercise
